# This workflow is meant to be triggered by push to master when running the release
# process.
#
# Don't extend this workflow. If any more steps are needed please extend the
# "publish-release" action in "z-quantum-actions". This allows reusing it between repos.
name: publish-release

on:
  push:
    branches:
      - master

jobs:
  run-action:
    runs-on: ubuntu-latest

    steps:
      # Needed to get access to publish-release action definition
      - name: Check out the released repo
        uses: actions/checkout@v2
        with:
          # Fetch whole repo to get access to tags. We need tags to read current package
          # version.
          fetch-depth: 0
      
      - name: Run publish release action
        uses: ./vendor/z-quantum-actions/publish-release
