# This is a basic workflow to help you get started with Actions

name: TestCoverage

# Triggers the workflow on push or pull to dev
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    container:
      image: zapatacomputing/qe-psi4:latest
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      # ------------------------------------------------------------------------
      # Only use ssh when a second private repo needs to be installed....
      # The current repo MUST have a secrets.SSH_PRIVATE_KEY defined in github.
      # ------------------------------------------------------------------------
      # - uses: ./subtrees/z_quantum_actions/actions/ssh_setup
      #   with:
      #     ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Get z-quantum-core
        uses: actions/checkout@v2
        with:
          repository: zapatacomputing/z-quantum-core
          path: z-quantum-core

      - name: Install make
        run: |
          apt-get install make

      - uses: ./subtrees/z_quantum_actions/actions/coverage
        with:
          codecov_secret: ${{ secrets.CODECOV_TOKEN }}
